// SD_CLI_FLAGS + SD_SERVER_FLAGS — the single source of truth for exposed flags.
// Audited against `sdcpp/bin/sd-cli -h` (commit 92a3b73) and
// examples/common/common.cpp (SDContextParams::get_options() /
// SDGenerationParams::get_options()) + examples/cli/main.cpp (SDCliParams).
// See PLAN.md §9 for the flag schema (mirrors LLama-GUI definitions.js).
//
// IMPORTANT upstream corrections vs. earlier placeholders (verified against -h):
//   - flash attention flag is `--fa` (NOT `--flash-attn`).
//   - there is NO `-ngl`/`--n-gpu-layers` in this build; GPU memory is managed
//     via `--offload-to-cpu`, `--backend`, `--params-backend`, `--max-vram`.
//   - there is NO `--format`; output format = extension of `--output`.
//   - metadata is embedded by default; the opt-out flag is
//     `--disable-image-metadata` (NOT `--embed-metadata`).
//   - img2img init image is `-i, --init-img` (NOT `--init-image`).
window.SDGui = window.SDGui || {};

// Each entry:
//   { id, flag, short, type, category, label, desc, default, mode, options?, backendOwned?, cliOnly? }
//   type ∈ bool | int | float | text | path | enum
//   mode  ∈ "all" | "img_gen" | "vid_gen" | "upscale" | "convert" | "metadata"
//   backendOwned: true  → the backend controls this arg; getLaunchArgs() skips it
//                         (e.g. --output / --preview-path naming for gallery sidecars).
window.SDGui.SD_CLI_FLAGS = [
	// ── Generation (img_gen) ────────────────────────────────────────────────
	{
		id: "prompt",
		flag: "--prompt",
		short: "-p",
		type: "text",
		category: "generation",
		label: "Prompt",
		desc: "The prompt to render.",
		default: "",
		mode: "img_gen",
	},
	{
		id: "negative_prompt",
		flag: "--negative-prompt",
		short: "-n",
		type: "text",
		category: "generation",
		label: "Negative prompt",
		desc: 'The negative prompt (default: "").',
		default: "",
		mode: "img_gen",
	},
	{
		id: "width",
		flag: "--width",
		short: "-W",
		type: "int",
		category: "generation",
		label: "Width",
		desc: "Image width, in pixel space.",
		default: 512,
		mode: "img_gen",
	},
	{
		id: "height",
		flag: "--height",
		short: "-H",
		type: "int",
		category: "generation",
		label: "Height",
		desc: "Image height, in pixel space.",
		default: 512,
		mode: "img_gen",
	},
	{
		id: "batch_count",
		flag: "--batch-count",
		short: "-b",
		type: "int",
		category: "generation",
		label: "Batch count",
		desc: "Number of images to generate.",
		default: 1,
		mode: "img_gen",
	},

	// ── Sampling (all generation modes) ────────────────────────────────────
	{
		id: "steps",
		flag: "--steps",
		type: "int",
		category: "sampling",
		label: "Steps",
		desc: "Number of sample steps (default: 20).",
		default: 20,
		mode: "all",
	},
	{
		id: "cfg_scale",
		flag: "--cfg-scale",
		type: "float",
		category: "sampling",
		label: "CFG scale",
		desc: "Unconditional guidance scale (default: 7.0).",
		default: 7.0,
		mode: "all",
	},
	{
		id: "sampling_method",
		flag: "--sampling-method",
		type: "enum",
		category: "sampling",
		label: "Sampling method",
		desc: "Denoising sampler (default: euler for Flux/SD3/Wan, euler_a otherwise).",
		default: "euler_a",
		mode: "all",
	},
	{
		id: "scheduler",
		flag: "--scheduler",
		type: "enum",
		category: "sampling",
		label: "Scheduler",
		desc: "Denoiser sigma scheduler (default: model-specific).",
		default: "default",
		mode: "all",
	},
	{
		id: "seed",
		flag: "--seed",
		short: "-s",
		type: "int",
		category: "sampling",
		label: "Seed",
		desc: "RNG seed (default: 42, use random seed for < 0).",
		default: 42,
		mode: "all",
	},
	{
		id: "rng",
		flag: "--rng",
		type: "enum",
		category: "sampling",
		label: "RNG",
		desc: "RNG, one of [cuda, std_default, cpu].",
		default: "cuda",
		mode: "all",
	},
	{
		id: "strength",
		flag: "--strength",
		type: "float",
		category: "sampling",
		label: "Strength",
		desc: "Strength for noising/unnoising (img2img, default: 0.75).",
		default: 0.75,
		mode: "img_gen",
	},

	// ── Model components (all) ──────────────────────────────────────────────
	{
		id: "model",
		flag: "--model",
		short: "-m",
		type: "path",
		category: "model_components",
		label: "Model",
		desc: "Path to full model.",
		default: "",
		mode: "all",
	},
	{
		id: "diffusion_model",
		flag: "--diffusion-model",
		type: "path",
		category: "model_components",
		label: "Diffusion model",
		desc: "Path to standalone diffusion model.",
		default: "",
		mode: "all",
	},
	{
		id: "vae",
		flag: "--vae",
		type: "path",
		category: "model_components",
		label: "VAE",
		desc: "Path to standalone VAE model.",
		default: "",
		mode: "all",
	},
	{
		id: "clip_l",
		flag: "--clip_l",
		type: "path",
		category: "model_components",
		label: "CLIP-L",
		desc: "Path to the clip-l text encoder.",
		default: "",
		mode: "all",
	},
	{
		id: "clip_g",
		flag: "--clip_g",
		type: "path",
		category: "model_components",
		label: "CLIP-G",
		desc: "Path to the clip-g text encoder.",
		default: "",
		mode: "all",
	},
	{
		id: "t5xxl",
		flag: "--t5xxl",
		type: "path",
		category: "model_components",
		label: "T5XXL",
		desc: "Path to the t5xxl text encoder.",
		default: "",
		mode: "all",
	},
	{
		id: "llm",
		flag: "--llm",
		type: "path",
		category: "model_components",
		label: "LLM text encoder",
		desc: "Path to the llm text encoder (e.g. qwenvl2.5 for qwen-image).",
		default: "",
		mode: "all",
	},
	{
		id: "taesd",
		flag: "--taesd",
		type: "path",
		category: "model_components",
		label: "TAESD",
		desc: "Path to taesd (Tiny AutoEncoder for fast preview/decode).",
		default: "",
		mode: "all",
	},
	{
		id: "control_net",
		flag: "--control-net",
		type: "path",
		category: "model_components",
		label: "ControlNet",
		desc: "Path to control net model.",
		default: "",
		mode: "all",
	},
	{
		id: "lora_model_dir",
		flag: "--lora-model-dir",
		type: "path",
		category: "model_components",
		label: "LoRA model dir",
		desc: "LoRA model directory.",
		default: "",
		mode: "all",
	},

	// ── Image-to-Image inputs (img_gen) ─────────────────────────────────────
	{
		id: "init_img",
		flag: "--init-img",
		short: "-i",
		type: "path",
		category: "img2img",
		label: "Init image",
		desc: "Path to the init image (img2img).",
		default: "",
		mode: "img_gen",
	},
	{
		id: "mask",
		flag: "--mask",
		type: "path",
		category: "img2img",
		label: "Mask",
		desc: "Path to the mask image (inpaint).",
		default: "",
		mode: "img_gen",
	},
	{
		id: "control_image",
		flag: "--control-image",
		type: "path",
		category: "img2img",
		label: "Control image",
		desc: "Path to control image (control net).",
		default: "",
		mode: "img_gen",
	},
	{
		id: "control_strength",
		flag: "--control-strength",
		type: "float",
		category: "img2img",
		label: "Control strength",
		desc: "Strength to apply Control Net (default: 0.9).",
		default: 0.9,
		mode: "img_gen",
	},

	// ── Backend & GPU (all) ─────────────────────────────────────────────────
	{
		id: "threads",
		flag: "--threads",
		short: "-t",
		type: "int",
		category: "backend_gpu",
		label: "Threads",
		desc: "Number of threads (default: -1 = number of physical CPU cores).",
		default: -1,
		mode: "all",
	},
	{
		id: "type",
		flag: "--type",
		type: "enum",
		category: "backend_gpu",
		label: "Weight type",
		desc: "Override weight type (f32/f16/q8_0/q4_0/...). Default = file type.",
		default: "default",
		mode: "all",
	},
	{
		id: "offload_to_cpu",
		flag: "--offload-to-cpu",
		type: "bool",
		category: "backend_gpu",
		label: "Offload to CPU",
		desc: "Place weights in RAM to save VRAM; load to VRAM when needed.",
		default: false,
		mode: "all",
	},
	{
		id: "clip_on_cpu",
		flag: "--clip-on-cpu",
		type: "bool",
		category: "backend_gpu",
		label: "CLIP on CPU",
		desc: "Keep text encoders on CPU (deprecated; prefer --backend te=cpu).",
		default: false,
		mode: "all",
	},
	{
		id: "vae_on_cpu",
		flag: "--vae-on-cpu",
		type: "bool",
		category: "backend_gpu",
		label: "VAE on CPU",
		desc: "Keep VAE on CPU (deprecated; prefer --backend vae=cpu).",
		default: false,
		mode: "all",
	},
	{
		id: "flash_attn",
		flag: "--fa",
		type: "bool",
		category: "backend_gpu",
		label: "Flash attention",
		desc: "Use flash attention.",
		default: false,
		mode: "all",
	},
	{
		id: "diffusion_fa",
		flag: "--diffusion-fa",
		type: "bool",
		category: "backend_gpu",
		label: "Diffusion flash attn",
		desc: "Use flash attention in the diffusion model only.",
		default: false,
		mode: "all",
	},
	{
		id: "backend",
		flag: "--backend",
		type: "text",
		category: "backend_gpu",
		label: "Backend assignment",
		desc: "Runtime backend assignment, e.g. cpu or clip=cpu,vae=cuda0,diffusion=vulkan0.",
		default: "",
		mode: "all",
	},
	{
		id: "params_backend",
		flag: "--params-backend",
		type: "text",
		category: "backend_gpu",
		label: "Params backend",
		desc: "Parameter backend assignment, e.g. disk, cpu, or diffusion=disk,clip=cpu.",
		default: "",
		mode: "all",
	},
	{
		id: "max_vram",
		flag: "--max-vram",
		type: "text",
		category: "backend_gpu",
		label: "Max VRAM (GiB)",
		desc: "Max VRAM budget in GiB for graph-cut execution (0 disables; negative auto-detects).",
		default: "",
		mode: "all",
	},
	{
		id: "vae_tiling",
		flag: "--vae-tiling",
		type: "bool",
		category: "backend_gpu",
		label: "VAE tiling",
		desc: "Process VAE in tiles to reduce memory usage.",
		default: false,
		mode: "all",
	},

	// ── Output / preview (all) ──────────────────────────────────────────────
	// --output / --preview-path are backendOwned: the backend always sets them so
	// it can reliably locate results + write gallery sidecars (PLAN.md §10).
	{
		id: "output",
		flag: "--output",
		short: "-o",
		type: "path",
		category: "output",
		label: "Output path",
		desc: "Result image path (printf %d for sequences). Backend-controlled.",
		default: "output.png",
		mode: "all",
		backendOwned: true,
	},
	{
		id: "preview_path",
		flag: "--preview-path",
		type: "path",
		category: "output",
		label: "Preview path",
		desc: "Path to write the preview image (backend-controlled).",
		default: "preview.png",
		mode: "all",
		backendOwned: true,
	},
	{
		id: "preview",
		flag: "--preview",
		type: "enum",
		category: "output",
		label: "Preview method",
		desc: "Preview method [none, proj, tae, vae]. Generate defaults to vae for live preview.",
		default: "none",
		mode: "all",
	},
	{
		id: "preview_interval",
		flag: "--preview-interval",
		type: "int",
		category: "output",
		label: "Preview interval",
		desc: "Denoising steps between preview updates (default: 1).",
		default: 1,
		mode: "all",
	},
	{
		id: "disable_image_metadata",
		flag: "--disable-image-metadata",
		type: "bool",
		category: "output",
		label: "Disable metadata",
		desc: "Do not embed generation metadata in output image files.",
		default: false,
		mode: "all",
	},
	{
		id: "verbose",
		flag: "--verbose",
		short: "-v",
		type: "bool",
		category: "output",
		label: "Verbose",
		desc: "Print extra info.",
		default: false,
		mode: "all",
	},
	{
		id: "color",
		flag: "--color",
		type: "bool",
		category: "output",
		label: "Color log",
		desc: "Color the logging tags according to level.",
		default: false,
		mode: "all",
	},
];

// Dedicated flag set for persistent sd-server (Phase 5). Left empty until then.
window.SDGui.SD_SERVER_FLAGS = [];
