// SD_CLI_FLAGS + SD_SERVER_FLAGS - the single source of truth for exposed flags.
// Audited against `sdcpp/bin/sd-cli -h` (stable-diffusion.cpp commit 92a3b73)
// and cross-checked against upstream examples/common/common.cpp + examples/cli/main.cpp.
//
// Notes from the audit:
//   - flash attention is `--fa`, not `--flash-attn`.
//   - there is no `--format`; output format follows the `--output` extension.
//   - output, preview path, and run mode are backend-owned for gallery safety.
//   - `mode` accepts either a string or an array of modes; array support is
//     needed because several flags apply to img_gen, vid_gen, and/or upscale.
window.SDGui = window.SDGui || {};

window.SDGui.SD_CLI_FLAGS = [
	// Generation inputs
	{
		id: "prompt",
		flag: "--prompt",
		short: "-p",
		type: "text",
		category: "generation",
		label: "Prompt",
		desc: "The prompt to render.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "negative_prompt",
		flag: "--negative-prompt",
		short: "-n",
		type: "text",
		category: "generation",
		label: "Negative prompt",
		desc: "The negative prompt.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "width",
		flag: "--width",
		short: "-W",
		type: "int",
		category: "generation",
		label: "Width",
		desc: "Image width in pixels.",
		default: 512,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "height",
		flag: "--height",
		short: "-H",
		type: "int",
		category: "generation",
		label: "Height",
		desc: "Image height in pixels.",
		default: 512,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "batch_count",
		flag: "--batch-count",
		short: "-b",
		type: "int",
		category: "generation",
		label: "Batch count",
		desc: "Number of images to generate.",
		default: 1,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "run_mode",
		flag: "--mode",
		short: "-M",
		type: "enum",
		category: "generation",
		label: "Run mode",
		desc: "sd-cli run mode. Backend-controlled from the Generate mode selector.",
		default: "img_gen",
		mode: "all",
		backendOwned: true,
	},
	{
		id: "clip_skip",
		flag: "--clip-skip",
		type: "int",
		category: "generation",
		label: "CLIP skip",
		desc: "Ignore last CLIP layers; <= 0 lets sd-cli choose.",
		default: -1,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "timestep_shift",
		flag: "--timestep-shift",
		type: "int",
		category: "generation",
		label: "Timestep shift",
		desc: "Shift timestep for NitroFusion models.",
		default: 0,
		mode: ["img_gen", "vid_gen"],
	},

	// Sampling
	{
		id: "steps",
		flag: "--steps",
		type: "int",
		category: "sampling",
		label: "Steps",
		desc: "Number of sample steps.",
		default: 20,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "cfg_scale",
		flag: "--cfg-scale",
		type: "float",
		category: "sampling",
		label: "CFG scale",
		desc: "Unconditional guidance scale.",
		default: 7.0,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "img_cfg_scale",
		flag: "--img-cfg-scale",
		type: "float",
		category: "sampling",
		label: "Image CFG scale",
		desc: "Image guidance scale for inpaint or image-edit models.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "guidance",
		flag: "--guidance",
		type: "float",
		category: "sampling",
		label: "Guidance",
		desc: "Distilled guidance scale for models with guidance input.",
		default: 3.5,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "slg_scale",
		flag: "--slg-scale",
		type: "float",
		category: "sampling",
		label: "SLG scale",
		desc: "Skip-layer guidance scale for DiT models; 0 disables it.",
		default: 0,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "skip_layer_start",
		flag: "--skip-layer-start",
		type: "float",
		category: "sampling",
		label: "SLG start",
		desc: "Skip-layer guidance enabling point.",
		default: 0.01,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "skip_layer_end",
		flag: "--skip-layer-end",
		type: "float",
		category: "sampling",
		label: "SLG end",
		desc: "Skip-layer guidance disabling point.",
		default: 0.2,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "eta",
		flag: "--eta",
		type: "float",
		category: "sampling",
		label: "Eta",
		desc: "Noise multiplier; default depends on sampler.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "flow_shift",
		flag: "--flow-shift",
		type: "float",
		category: "sampling",
		label: "Flow shift",
		desc: "Shift value for Flow models like SD3.x or Wan; blank means auto.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "sampling_method",
		flag: "--sampling-method",
		type: "enum",
		category: "sampling",
		label: "Sampling method",
		desc: "Denoising sampler.",
		default: "euler_a",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "scheduler",
		flag: "--scheduler",
		type: "enum",
		category: "sampling",
		label: "Scheduler",
		desc: "Denoiser sigma scheduler; default is model-specific.",
		default: "default",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "seed",
		flag: "--seed",
		short: "-s",
		type: "int",
		category: "sampling",
		label: "Seed",
		desc: "RNG seed; use a negative value for random.",
		default: 42,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "rng",
		flag: "--rng",
		type: "enum",
		category: "sampling",
		label: "RNG",
		desc: "RNG type.",
		default: "cuda",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "sampler_rng",
		flag: "--sampler-rng",
		type: "enum",
		category: "sampling",
		label: "Sampler RNG",
		desc: "Sampler RNG type; defaults to --rng when not specified.",
		default: "",
		mode: ["img_gen", "vid_gen"],
		options: ["", "cuda", "std_default", "cpu"],
	},
	{
		id: "sigmas",
		flag: "--sigmas",
		type: "text",
		category: "sampling",
		label: "Sigmas",
		desc: "Custom sigma values for the sampler, comma-separated.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "skip_layers",
		flag: "--skip-layers",
		type: "text",
		category: "sampling",
		label: "SLG skip layers",
		desc: "Layers to skip for SLG steps.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "extra_sample_args",
		flag: "--extra-sample-args",
		type: "text",
		category: "sampling",
		label: "Extra sample args",
		desc: "Extra sampler, scheduler, or guidance args as key=value pairs.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},

	// High-noise / dual-model sampling
	{
		id: "high_noise_diffusion_model",
		flag: "--high-noise-diffusion-model",
		type: "path",
		category: "model_components",
		label: "High-noise diffusion model",
		desc: "Standalone high-noise diffusion model.",
		default: "",
		mode: "all",
	},
	{
		id: "uncond_diffusion_model",
		flag: "--uncond-diffusion-model",
		type: "path",
		category: "model_components",
		label: "Unconditional diffusion model",
		desc: "Standalone unconditional diffusion model, currently used by Ideogram4 CFG.",
		default: "",
		mode: "all",
	},
	{
		id: "high_noise_steps",
		flag: "--high-noise-steps",
		type: "int",
		category: "advanced",
		label: "High-noise steps",
		desc: "High-noise sample steps; -1 means auto.",
		default: -1,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "high_noise_cfg_scale",
		flag: "--high-noise-cfg-scale",
		type: "float",
		category: "advanced",
		label: "High-noise CFG",
		desc: "High-noise unconditional guidance scale.",
		default: 7.0,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "high_noise_img_cfg_scale",
		flag: "--high-noise-img-cfg-scale",
		type: "float",
		category: "advanced",
		label: "High-noise image CFG",
		desc: "High-noise image guidance scale.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "high_noise_guidance",
		flag: "--high-noise-guidance",
		type: "float",
		category: "advanced",
		label: "High-noise guidance",
		desc: "High-noise distilled guidance scale.",
		default: 3.5,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "high_noise_slg_scale",
		flag: "--high-noise-slg-scale",
		type: "float",
		category: "advanced",
		label: "High-noise SLG scale",
		desc: "High-noise skip-layer guidance scale.",
		default: 0,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "high_noise_skip_layer_start",
		flag: "--high-noise-skip-layer-start",
		type: "float",
		category: "advanced",
		label: "High-noise SLG start",
		desc: "High-noise SLG enabling point.",
		default: 0.01,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "high_noise_skip_layer_end",
		flag: "--high-noise-skip-layer-end",
		type: "float",
		category: "advanced",
		label: "High-noise SLG end",
		desc: "High-noise SLG disabling point.",
		default: 0.2,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "high_noise_eta",
		flag: "--high-noise-eta",
		type: "float",
		category: "advanced",
		label: "High-noise eta",
		desc: "High-noise noise multiplier.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "high_noise_sampling_method",
		flag: "--high-noise-sampling-method",
		type: "enum",
		category: "advanced",
		label: "High-noise sampler",
		desc: "High-noise sampling method.",
		default: "euler_a",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "high_noise_skip_layers",
		flag: "--high-noise-skip-layers",
		type: "text",
		category: "advanced",
		label: "High-noise skip layers",
		desc: "Layers to skip for high-noise SLG steps.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},

	// Model components
	{
		id: "model",
		flag: "--model",
		short: "-m",
		type: "path",
		category: "model_components",
		label: "Model",
		desc: "Path to a full model.",
		default: "",
		mode: "all",
	},
	{
		id: "diffusion_model",
		flag: "--diffusion-model",
		type: "path",
		category: "model_components",
		label: "Diffusion model",
		desc: "Path to a standalone diffusion model.",
		default: "",
		mode: "all",
	},
	{
		id: "vae",
		flag: "--vae",
		type: "path",
		category: "model_components",
		label: "VAE",
		desc: "Path to a standalone VAE model.",
		default: "",
		mode: "all",
	},
	{
		id: "vae_format",
		flag: "--vae-format",
		type: "enum",
		category: "model_components",
		label: "VAE format",
		desc: "VAE latent format override.",
		default: "auto",
		mode: "all",
	},
	{
		id: "audio_vae",
		flag: "--audio-vae",
		type: "path",
		category: "model_components",
		label: "Audio VAE",
		desc: "Path to a standalone LTX audio VAE model.",
		default: "",
		mode: "all",
	},
	{
		id: "clip_l",
		flag: "--clip_l",
		type: "path",
		category: "model_components",
		label: "CLIP-L",
		desc: "Path to the CLIP-L text encoder.",
		default: "",
		mode: "all",
	},
	{
		id: "clip_g",
		flag: "--clip_g",
		type: "path",
		category: "model_components",
		label: "CLIP-G",
		desc: "Path to the CLIP-G text encoder.",
		default: "",
		mode: "all",
	},
	{
		id: "clip_vision",
		flag: "--clip_vision",
		type: "path",
		category: "model_components",
		label: "CLIP vision",
		desc: "Path to the CLIP vision encoder.",
		default: "",
		mode: "all",
	},
	{
		id: "t5xxl",
		flag: "--t5xxl",
		type: "path",
		category: "model_components",
		label: "T5XXL",
		desc: "Path to the T5XXL text encoder.",
		default: "",
		mode: "all",
	},
	{
		id: "llm",
		flag: "--llm",
		type: "path",
		category: "model_components",
		label: "LLM text encoder",
		desc: "Path to the LLM text encoder.",
		default: "",
		mode: "all",
	},
	{
		id: "llm_vision",
		flag: "--llm_vision",
		type: "path",
		category: "model_components",
		label: "LLM vision",
		desc: "Path to the LLM vision encoder.",
		default: "",
		mode: "all",
	},
	{
		id: "qwen2vl",
		flag: "--qwen2vl",
		type: "path",
		category: "model_components",
		label: "Qwen2VL alias",
		desc: "Deprecated alias of --llm.",
		default: "",
		mode: "all",
	},
	{
		id: "qwen2vl_vision",
		flag: "--qwen2vl_vision",
		type: "path",
		category: "model_components",
		label: "Qwen2VL vision alias",
		desc: "Deprecated alias of --llm_vision.",
		default: "",
		mode: "all",
	},
	{
		id: "taesd",
		flag: "--taesd",
		type: "path",
		category: "model_components",
		label: "TAESD",
		desc: "Path to TAESD for fast low-quality decoding.",
		default: "",
		mode: "all",
	},
	{
		id: "tae",
		flag: "--tae",
		type: "path",
		category: "model_components",
		label: "TAE alias",
		desc: "Alias of --taesd.",
		default: "",
		mode: "all",
	},
	{
		id: "control_net",
		flag: "--control-net",
		type: "path",
		category: "model_components",
		label: "ControlNet",
		desc: "Path to a ControlNet model.",
		default: "",
		mode: "all",
	},
	{
		id: "embeddings_connectors",
		flag: "--embeddings-connectors",
		type: "path",
		category: "model_components",
		label: "Embeddings connectors",
		desc: "Path to LTXAV embeddings connectors.",
		default: "",
		mode: "all",
	},
	{
		id: "embd_dir",
		flag: "--embd-dir",
		type: "path",
		category: "model_components",
		label: "Embeddings dir",
		desc: "Embeddings directory.",
		default: "",
		mode: "all",
	},
	{
		id: "lora_model_dir",
		flag: "--lora-model-dir",
		type: "path",
		category: "lora",
		label: "LoRA model dir",
		desc: "LoRA model directory.",
		default: "",
		mode: "all",
	},
	{
		id: "hires_upscalers_dir",
		flag: "--hires-upscalers-dir",
		type: "path",
		category: "model_components",
		label: "Hires upscalers dir",
		desc: "Highres fix upscaler model directory.",
		default: "",
		mode: "all",
	},
	{
		id: "upscale_model",
		flag: "--upscale-model",
		type: "path",
		category: "model_components",
		label: "Upscale model",
		desc: "Path to ESRGAN upscaler model.",
		default: "",
		mode: "upscale",
	},

	// Image-to-image, control, references
	{
		id: "init_img",
		flag: "--init-img",
		short: "-i",
		type: "path",
		category: "img2img",
		label: "Init image",
		desc: "Path to the init image.",
		default: "",
		mode: ["img_gen", "vid_gen", "upscale"],
	},
	{
		id: "end_img",
		flag: "--end-img",
		type: "path",
		category: "img2img",
		label: "End image",
		desc: "Path to the end image, required by flf2v.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "mask",
		flag: "--mask",
		type: "path",
		category: "img2img",
		label: "Mask",
		desc: "Path to the mask image.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "control_image",
		flag: "--control-image",
		type: "path",
		category: "img2img",
		label: "Control image",
		desc: "Path to a ControlNet image.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "control_video",
		flag: "--control-video",
		type: "path",
		category: "video",
		label: "Control video frames",
		desc: "Directory of control video frame images in lexicographic order.",
		default: "",
		mode: "vid_gen",
	},
	{
		id: "control_strength",
		flag: "--control-strength",
		type: "float",
		category: "img2img",
		label: "Control strength",
		desc: "Strength to apply ControlNet.",
		default: 0.9,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "strength",
		flag: "--strength",
		type: "float",
		category: "img2img",
		label: "Strength",
		desc: "Strength for noising/unnoising.",
		default: 0.75,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "ref_image",
		flag: "--ref-image",
		short: "-r",
		type: "path",
		category: "img2img",
		label: "Reference image",
		desc: "Reference image for Flux Kontext; use custom args for multiple images.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "increase_ref_index",
		flag: "--increase-ref-index",
		type: "bool",
		category: "img2img",
		label: "Increase ref index",
		desc: "Automatically increase reference image indices based on order.",
		default: false,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "disable_auto_resize_ref_image",
		flag: "--disable-auto-resize-ref-image",
		type: "bool",
		category: "img2img",
		label: "Disable ref auto-resize",
		desc: "Disable automatic resizing of reference images.",
		default: false,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "canny",
		flag: "--canny",
		type: "bool",
		category: "img2img",
		label: "Canny preprocessor",
		desc: "Apply Canny edge detection preprocessor.",
		default: false,
		mode: ["img_gen", "vid_gen"],
	},

	// LoRA, PhotoMaker, PuLID
	{
		id: "lora_apply_mode",
		flag: "--lora-apply-mode",
		type: "enum",
		category: "lora",
		label: "LoRA apply mode",
		desc: "How LoRA weights are applied.",
		default: "auto",
		mode: "all",
	},
	{
		id: "photo_maker",
		flag: "--photo-maker",
		type: "path",
		category: "lora",
		label: "PhotoMaker",
		desc: "Path to a PhotoMaker model.",
		default: "",
		mode: "all",
	},
	{
		id: "pm_id_images_dir",
		flag: "--pm-id-images-dir",
		type: "path",
		category: "lora",
		label: "PhotoMaker ID images",
		desc: "Path to the PhotoMaker input ID images directory.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "pm_id_embed_path",
		flag: "--pm-id-embed-path",
		type: "path",
		category: "lora",
		label: "PhotoMaker ID embed",
		desc: "Path to the PhotoMaker v2 ID embedding.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "pm_style_strength",
		flag: "--pm-style-strength",
		type: "float",
		category: "lora",
		label: "PhotoMaker style strength",
		desc: "PhotoMaker style strength.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "pulid_weights",
		flag: "--pulid-weights",
		type: "path",
		category: "lora",
		label: "PuLID weights",
		desc: "Path to PuLID Flux weights.",
		default: "",
		mode: "all",
	},
	{
		id: "pulid_id_embedding",
		flag: "--pulid-id-embedding",
		type: "path",
		category: "lora",
		label: "PuLID ID embedding",
		desc: "Path to a PuLID ID embedding.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "pulid_id_weight",
		flag: "--pulid-id-weight",
		type: "float",
		category: "lora",
		label: "PuLID ID weight",
		desc: "Strength of PuLID identity injection.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},

	// Video
	{
		id: "video_frames",
		flag: "--video-frames",
		type: "int",
		category: "video",
		label: "Video frames",
		desc: "Number of video frames.",
		default: 1,
		mode: "vid_gen",
	},
	{
		id: "fps",
		flag: "--fps",
		type: "int",
		category: "video",
		label: "FPS",
		desc: "Frames per second.",
		default: 24,
		mode: "vid_gen",
	},
	{
		id: "vace_strength",
		flag: "--vace-strength",
		type: "float",
		category: "video",
		label: "VACE strength",
		desc: "Wan VACE strength.",
		default: "",
		mode: "vid_gen",
	},
	{
		id: "moe_boundary",
		flag: "--moe-boundary",
		type: "float",
		category: "video",
		label: "MoE boundary",
		desc: "Wan2.2 MoE timestep boundary.",
		default: 0.875,
		mode: "vid_gen",
	},
	{
		id: "temporal_tiling",
		flag: "--temporal-tiling",
		type: "bool",
		category: "video",
		label: "Temporal tiling",
		desc: "Enable temporal tiling for LTX video VAE decode.",
		default: false,
		mode: "vid_gen",
	},
	{
		id: "extra_tiling_args",
		flag: "--extra-tiling-args",
		type: "text",
		category: "video",
		label: "Extra tiling args",
		desc: "Extra VAE tiling args as key=value pairs.",
		default: "",
		mode: "vid_gen",
	},

	// Upscale / convert / metadata modes
	{
		id: "upscale_repeats",
		flag: "--upscale-repeats",
		type: "int",
		category: "img2img",
		label: "Upscale repeats",
		desc: "Run the ESRGAN upscaler this many times.",
		default: 1,
		mode: "upscale",
	},
	{
		id: "upscale_tile_size",
		flag: "--upscale-tile-size",
		type: "int",
		category: "img2img",
		label: "Upscale tile size",
		desc: "Tile size for ESRGAN upscaling.",
		default: 128,
		mode: "upscale",
	},
	{
		id: "convert_name",
		flag: "--convert-name",
		type: "text",
		category: "advanced",
		label: "Convert tensor name",
		desc: "Convert a single tensor name.",
		default: "",
		mode: "convert",
	},
	{
		id: "image",
		flag: "--image",
		type: "path",
		category: "img2img",
		label: "Image",
		desc: "Path to the image to inspect.",
		default: "",
		mode: "metadata",
	},
	{
		id: "metadata_format",
		flag: "--metadata-format",
		type: "enum",
		category: "output",
		label: "Metadata format",
		desc: "Metadata output format.",
		default: "text",
		mode: "metadata",
	},
	{
		id: "metadata_raw",
		flag: "--metadata-raw",
		type: "bool",
		category: "output",
		label: "Raw metadata",
		desc: "Include raw hex previews for unparsed metadata payloads.",
		default: false,
		mode: "metadata",
	},
	{
		id: "metadata_brief",
		flag: "--metadata-brief",
		type: "bool",
		category: "output",
		label: "Brief metadata",
		desc: "Truncate long metadata text values in text output.",
		default: false,
		mode: "metadata",
	},
	{
		id: "metadata_all",
		flag: "--metadata-all",
		type: "bool",
		category: "output",
		label: "All metadata chunks",
		desc: "Include structural/container entries and non-metadata JPEG segments.",
		default: false,
		mode: "metadata",
	},

	// Highres fix
	{
		id: "hires",
		flag: "--hires",
		type: "bool",
		category: "advanced",
		label: "Highres fix",
		desc: "Enable highres fix.",
		default: false,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "hires_upscaler",
		flag: "--hires-upscaler",
		type: "text",
		category: "advanced",
		label: "Highres upscaler",
		desc: "Highres fix upscaler name.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "hires_width",
		flag: "--hires-width",
		type: "int",
		category: "advanced",
		label: "Highres width",
		desc: "Highres fix target width; 0 uses --hires-scale.",
		default: 0,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "hires_height",
		flag: "--hires-height",
		type: "int",
		category: "advanced",
		label: "Highres height",
		desc: "Highres fix target height; 0 uses --hires-scale.",
		default: 0,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "hires_steps",
		flag: "--hires-steps",
		type: "int",
		category: "advanced",
		label: "Highres steps",
		desc: "Highres fix second-pass sample steps; 0 reuses --steps.",
		default: 0,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "hires_upscale_tile_size",
		flag: "--hires-upscale-tile-size",
		type: "int",
		category: "advanced",
		label: "Highres tile size",
		desc: "Highres fix upscaler tile size.",
		default: 128,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "hires_scale",
		flag: "--hires-scale",
		type: "float",
		category: "advanced",
		label: "Highres scale",
		desc: "Highres fix scale when target size is not set.",
		default: 2.0,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "hires_denoising_strength",
		flag: "--hires-denoising-strength",
		type: "float",
		category: "advanced",
		label: "Highres denoise",
		desc: "Highres fix second-pass denoising strength.",
		default: 0.7,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "hires_sigmas",
		flag: "--hires-sigmas",
		type: "text",
		category: "advanced",
		label: "Highres sigmas",
		desc: "Custom sigma values for the highres second pass.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},

	// Backend and memory
	{
		id: "threads",
		flag: "--threads",
		short: "-t",
		type: "int",
		category: "backend_gpu",
		label: "Threads",
		desc: "Number of CPU threads; <= 0 uses physical cores.",
		default: -1,
		mode: "all",
	},
	{
		id: "backend",
		flag: "--backend",
		type: "text",
		category: "backend_gpu",
		label: "Backend assignment",
		desc: "Runtime backend assignment, e.g. cpu or clip=cpu,vae=cuda0.",
		default: "",
		mode: "all",
	},
	{
		id: "params_backend",
		flag: "--params-backend",
		type: "text",
		category: "backend_gpu",
		label: "Params backend",
		desc: "Parameter backend assignment, e.g. disk, cpu, or diffusion=disk.",
		default: "",
		mode: "all",
	},
	{
		id: "rpc_servers",
		flag: "--rpc-servers",
		type: "text",
		category: "backend_gpu",
		label: "RPC servers",
		desc: "Comma-separated RPC offload servers in host:port format.",
		default: "",
		mode: "all",
	},
	{
		id: "max_vram",
		flag: "--max-vram",
		type: "text",
		category: "backend_gpu",
		label: "Max VRAM",
		desc: "VRAM budget in GiB or per-device assignments.",
		default: "",
		mode: "all",
	},
	{
		id: "stream_layers",
		flag: "--stream-layers",
		type: "bool",
		category: "backend_gpu",
		label: "Stream layers",
		desc: "Enable residency and prefetch streaming on top of --max-vram.",
		default: false,
		mode: "all",
	},
	{
		id: "offload_to_cpu",
		flag: "--offload-to-cpu",
		type: "bool",
		category: "backend_gpu",
		label: "Offload to CPU",
		desc: "Keep weights in RAM and load to VRAM when needed.",
		default: false,
		mode: "all",
	},
	{
		id: "mmap",
		flag: "--mmap",
		type: "bool",
		category: "backend_gpu",
		label: "Memory-map model",
		desc: "Memory-map model files.",
		default: false,
		mode: "all",
	},
	{
		id: "control_net_cpu",
		flag: "--control-net-cpu",
		type: "bool",
		category: "backend_gpu",
		label: "ControlNet on CPU",
		desc: "Deprecated; prefer --backend controlnet=cpu.",
		default: false,
		mode: "all",
	},
	{
		id: "clip_on_cpu",
		flag: "--clip-on-cpu",
		type: "bool",
		category: "backend_gpu",
		label: "CLIP on CPU",
		desc: "Deprecated; prefer --backend te=cpu.",
		default: false,
		mode: "all",
	},
	{
		id: "vae_on_cpu",
		flag: "--vae-on-cpu",
		type: "bool",
		category: "backend_gpu",
		label: "VAE on CPU",
		desc: "Deprecated; prefer --backend vae=cpu.",
		default: false,
		mode: "all",
	},
	{
		id: "flash_attn",
		flag: "--fa",
		type: "bool",
		category: "backend_gpu",
		label: "Flash attention",
		desc: "Use flash attention.",
		default: false,
		mode: "all",
	},
	{
		id: "diffusion_fa",
		flag: "--diffusion-fa",
		type: "bool",
		category: "backend_gpu",
		label: "Diffusion flash attn",
		desc: "Use flash attention in the diffusion model only.",
		default: false,
		mode: "all",
	},
	{
		id: "diffusion_conv_direct",
		flag: "--diffusion-conv-direct",
		type: "bool",
		category: "backend_gpu",
		label: "Diffusion direct conv",
		desc: "Use ggml_conv2d_direct in the diffusion model.",
		default: false,
		mode: "all",
	},
	{
		id: "vae_conv_direct",
		flag: "--vae-conv-direct",
		type: "bool",
		category: "backend_gpu",
		label: "VAE direct conv",
		desc: "Use ggml_conv2d_direct in the VAE model.",
		default: false,
		mode: "all",
	},
	{
		id: "force_sdxl_vae_conv_scale",
		flag: "--force-sdxl-vae-conv-scale",
		type: "bool",
		category: "backend_gpu",
		label: "Force SDXL VAE conv scale",
		desc: "Force use of convolution scale on SDXL VAE.",
		default: false,
		mode: "all",
	},
	{
		id: "vae_tiling",
		flag: "--vae-tiling",
		type: "bool",
		category: "backend_gpu",
		label: "VAE tiling",
		desc: "Process VAE in tiles to reduce memory usage.",
		default: false,
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "vae_tile_size",
		flag: "--vae-tile-size",
		type: "text",
		category: "backend_gpu",
		label: "VAE tile size",
		desc: "VAE tiling size in XxY format.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "vae_relative_tile_size",
		flag: "--vae-relative-tile-size",
		type: "text",
		category: "backend_gpu",
		label: "VAE relative tile size",
		desc: "Relative VAE tile size in XxY format.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "vae_tile_overlap",
		flag: "--vae-tile-overlap",
		type: "float",
		category: "backend_gpu",
		label: "VAE tile overlap",
		desc: "VAE tile overlap as a fraction of tile size.",
		default: 0.5,
		mode: ["img_gen", "vid_gen"],
	},

	// Advanced model behavior
	{
		id: "type",
		flag: "--type",
		type: "enum",
		category: "advanced",
		label: "Weight type",
		desc: "Override weight type; blank/default uses the weight file type.",
		default: "default",
		mode: "all",
	},
	{
		id: "tensor_type_rules",
		flag: "--tensor-type-rules",
		type: "text",
		category: "advanced",
		label: "Tensor type rules",
		desc: "Weight type per tensor pattern, e.g. ^vae\\.=f16,model\\.=q8_0.",
		default: "",
		mode: "all",
	},
	{
		id: "prediction",
		flag: "--prediction",
		type: "enum",
		category: "advanced",
		label: "Prediction type",
		desc: "Prediction type override.",
		default: "default",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "chroma_t5_mask_pad",
		flag: "--chroma-t5-mask-pad",
		type: "int",
		category: "advanced",
		label: "Chroma T5 mask pad",
		desc: "T5 mask pad size for Chroma.",
		default: "",
		mode: "all",
	},
	{
		id: "circular",
		flag: "--circular",
		type: "bool",
		category: "advanced",
		label: "Circular padding",
		desc: "Enable circular padding for convolutions.",
		default: false,
		mode: "all",
	},
	{
		id: "circularx",
		flag: "--circularx",
		type: "bool",
		category: "advanced",
		label: "Circular X",
		desc: "Enable circular RoPE wrapping on the x-axis only.",
		default: false,
		mode: "all",
	},
	{
		id: "circulary",
		flag: "--circulary",
		type: "bool",
		category: "advanced",
		label: "Circular Y",
		desc: "Enable circular RoPE wrapping on the y-axis only.",
		default: false,
		mode: "all",
	},
	{
		id: "chroma_disable_dit_mask",
		flag: "--chroma-disable-dit-mask",
		type: "bool",
		category: "advanced",
		label: "Disable Chroma DiT mask",
		desc: "Disable DiT mask for Chroma.",
		default: false,
		mode: "all",
	},
	{
		id: "qwen_image_zero_cond_t",
		flag: "--qwen-image-zero-cond-t",
		type: "bool",
		category: "advanced",
		label: "Qwen zero cond t",
		desc: "Enable zero_cond_t for Qwen Image.",
		default: false,
		mode: "all",
	},
	{
		id: "chroma_enable_t5_mask",
		flag: "--chroma-enable-t5-mask",
		type: "bool",
		category: "advanced",
		label: "Chroma T5 mask",
		desc: "Enable T5 mask for Chroma.",
		default: false,
		mode: "all",
	},

	// Cache controls
	{
		id: "cache_mode",
		flag: "--cache-mode",
		type: "text",
		category: "advanced",
		label: "Cache mode",
		desc: "Caching method such as easycache, ucache, dbcache, taylorseer, cache-dit, or spectrum.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "cache_option",
		flag: "--cache-option",
		type: "text",
		category: "advanced",
		label: "Cache options",
		desc: "Named cache parameters as comma-separated key=value pairs.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "scm_mask",
		flag: "--scm-mask",
		type: "text",
		category: "advanced",
		label: "SCM mask",
		desc: "SCM steps mask for cache-dit as comma-separated 0/1 values.",
		default: "",
		mode: ["img_gen", "vid_gen"],
	},
	{
		id: "scm_policy",
		flag: "--scm-policy",
		type: "enum",
		category: "advanced",
		label: "SCM policy",
		desc: "SCM cache policy.",
		default: "dynamic",
		mode: ["img_gen", "vid_gen"],
	},

	// Output, preview, metadata
	{
		id: "output",
		flag: "--output",
		short: "-o",
		type: "path",
		category: "output",
		label: "Output path",
		desc: "Result path. Backend-controlled so gallery sidecars can find outputs.",
		default: "output.png",
		mode: "all",
		backendOwned: true,
	},
	{
		id: "output_begin_idx",
		flag: "--output-begin-idx",
		type: "int",
		category: "output",
		label: "Output begin index",
		desc: "Starting index for output image sequences.",
		default: "",
		mode: "all",
	},
	{
		id: "preview_path",
		flag: "--preview-path",
		type: "path",
		category: "output",
		label: "Preview path",
		desc: "Preview image path. Backend-controlled.",
		default: "preview.png",
		mode: "all",
		backendOwned: true,
	},
	{
		id: "preview",
		flag: "--preview",
		type: "enum",
		category: "output",
		label: "Preview method",
		desc: "Preview method used while generating.",
		default: "none",
		mode: "all",
	},
	{
		id: "preview_interval",
		flag: "--preview-interval",
		type: "int",
		category: "output",
		label: "Preview interval",
		desc: "Denoising steps between preview file updates.",
		default: 1,
		mode: "all",
	},
	{
		id: "taesd_preview_only",
		flag: "--taesd-preview-only",
		type: "bool",
		category: "output",
		label: "TAESD preview only",
		desc: "Prevent TAESD from decoding the final image.",
		default: false,
		mode: "all",
	},
	{
		id: "preview_noisy",
		flag: "--preview-noisy",
		type: "bool",
		category: "output",
		label: "Preview noisy",
		desc: "Preview noisy model inputs instead of denoised outputs.",
		default: false,
		mode: "all",
	},
	{
		id: "disable_image_metadata",
		flag: "--disable-image-metadata",
		type: "bool",
		category: "output",
		label: "Disable metadata",
		desc: "Do not embed generation metadata in output image files.",
		default: false,
		mode: "all",
	},
	{
		id: "verbose",
		flag: "--verbose",
		short: "-v",
		type: "bool",
		category: "output",
		label: "Verbose",
		desc: "Print extra info.",
		default: false,
		mode: "all",
	},
	{
		id: "color",
		flag: "--color",
		type: "bool",
		category: "output",
		label: "Color log",
		desc: "Color logging tags by level.",
		default: false,
		mode: "all",
	},
];

// Dedicated flag set for persistent sd-server (Phase 5).
window.SDGui.SD_SERVER_FLAGS = [];
