// SD_CLI_FLAGS + SD_SERVER_FLAGS — the single source of truth for exposed flags.
// TODO(Phase 2/4): populate by auditing `sd-cli -h` / examples/common/common.cpp.
// See PLAN.md §9 for the flag schema (mirrors LLama-GUI definitions.js).

window.SDGui = window.SDGui || {};

// Each entry: { id, flag, short, type, category, label, desc, default, mode }
// type ∈ bool | int | float | text | path | enum | multi_enum
// mode ∈ "all" | "img_gen" | "vid_gen" | "upscale" | "convert" | "metadata"
window.SDGui.SD_CLI_FLAGS = [
	// Generation (core) — placeholders until the Phase 2 audit.
	{
		id: "prompt",
		flag: "--prompt",
		short: "-p",
		type: "text",
		category: "generation",
		label: "Prompt",
		desc: "the prompt to render",
		default: "",
		mode: "img_gen",
	},
	{
		id: "negative_prompt",
		flag: "--negative-prompt",
		short: "-n",
		type: "text",
		category: "generation",
		label: "Negative prompt",
		desc: "the negative prompt",
		default: "",
		mode: "img_gen",
	},
	{
		id: "width",
		flag: "--width",
		short: "-W",
		type: "int",
		category: "generation",
		label: "Width",
		desc: "image width",
		default: 512,
		mode: "img_gen",
	},
	{
		id: "height",
		flag: "--height",
		short: "-H",
		type: "int",
		category: "generation",
		label: "Height",
		desc: "image height",
		default: 512,
		mode: "img_gen",
	},
	{
		id: "steps",
		flag: "--steps",
		type: "int",
		category: "sampling",
		label: "Steps",
		desc: "number of sample steps",
		default: 20,
		mode: "all",
	},
	{
		id: "cfg_scale",
		flag: "--cfg-scale",
		type: "float",
		category: "sampling",
		label: "CFG scale",
		desc: "unconditional guidance scale",
		default: 7.0,
		mode: "all",
	},
	{
		id: "seed",
		flag: "--seed",
		short: "-s",
		type: "int",
		category: "sampling",
		label: "Seed",
		desc: "random seed (-1 = random)",
		default: 42,
		mode: "all",
	},
	{
		id: "batch_count",
		flag: "--batch-count",
		short: "-b",
		type: "int",
		category: "generation",
		label: "Batch count",
		desc: "number of images to generate",
		default: 1,
		mode: "img_gen",
	},
	// Model components
	{
		id: "model",
		flag: "--model",
		short: "-m",
		type: "path",
		category: "model_components",
		label: "Model",
		desc: "path to full model",
		default: "",
		mode: "all",
	},
	{
		id: "diffusion_model",
		flag: "--diffusion-model",
		type: "path",
		category: "model_components",
		label: "Diffusion model",
		desc: "path to standalone diffusion model",
		default: "",
		mode: "all",
	},
	{
		id: "vae",
		flag: "--vae",
		type: "path",
		category: "model_components",
		label: "VAE",
		desc: "path to VAE",
		default: "",
		mode: "all",
	},
	{
		id: "clip_l",
		flag: "--clip_l",
		type: "path",
		category: "model_components",
		label: "CLIP-L",
		desc: "path to clip_l",
		default: "",
		mode: "all",
	},
	{
		id: "clip_g",
		flag: "--clip_g",
		type: "path",
		category: "model_components",
		label: "CLIP-G",
		desc: "path to clip_g",
		default: "",
		mode: "all",
	},
	{
		id: "t5xxl",
		flag: "--t5xxl",
		type: "path",
		category: "model_components",
		label: "T5XXL",
		desc: "path to t5xxl",
		default: "",
		mode: "all",
	},
	{
		id: "llm",
		flag: "--llm",
		type: "path",
		category: "model_components",
		label: "LLM text encoder",
		desc: "path to LLM text encoder",
		default: "",
		mode: "all",
	},
	// Backend / GPU
	{
		id: "ngl",
		flag: "--ngl",
		short: "-ngl",
		type: "int",
		category: "backend_gpu",
		label: "GPU layers",
		desc: "number of layers to offload to GPU",
		default: 0,
		mode: "all",
	},
	{
		id: "threads",
		flag: "--threads",
		short: "-t",
		type: "int",
		category: "backend_gpu",
		label: "Threads",
		desc: "number of threads (-1 = auto)",
		default: -1,
		mode: "all",
	},
	{
		id: "flash_attn",
		flag: "--flash-attn",
		type: "bool",
		category: "backend_gpu",
		label: "Flash attention",
		desc: "enable flash attention",
		default: false,
		mode: "all",
	},
	{
		id: "clip_on_cpu",
		flag: "--clip-on-cpu",
		type: "bool",
		category: "backend_gpu",
		label: "CLIP on CPU",
		desc: "keep text encoders on CPU",
		default: false,
		mode: "all",
	},
	{
		id: "offload_to_cpu",
		flag: "--offload-to-cpu",
		type: "bool",
		category: "backend_gpu",
		label: "Offload to CPU",
		desc: "offload weights to CPU to save VRAM",
		default: false,
		mode: "all",
	},
	// Output
	{
		id: "output",
		flag: "--output",
		short: "-o",
		type: "path",
		category: "output",
		label: "Output path",
		desc: "result image path (printf %d for sequences)",
		default: "output.png",
		mode: "all",
	},
	{
		id: "verbose",
		flag: "--verbose",
		short: "-v",
		type: "bool",
		category: "output",
		label: "Verbose",
		desc: "print extra info",
		default: true,
		mode: "all",
	},
];

// Dedicated flag set for persistent sd-server (Phase 5).
window.SDGui.SD_SERVER_FLAGS = [];
